抽屉动画
cloudreve/frontend pull request #70
Opened 2021-04-08 10:07 UTC by Aruelius

打开关闭抽屉不再直接原地消失

2021-04-25 14:51 UTC, HFO4 commented
我这边好像一直是正常的(?)

2021-04-25 15:16 UTC, Aruelius commented
有动画：https://codesandbox.io/s/material-demo-forked-7lhj2?file=/demo.js
对比一下没动画的抽屉：https://demo.cloudreve.org/login

2021-04-26 12:20 UTC, HFO4 requested changes

2021-04-26 12:20 UTC, HFO4 commented on src/component/Navbar/Navbar.js
> +                            paper: classes.drawerPaper,
这里不应该用 `drawerPaper`，因为`drawerPaper`定义的宽度是移动端使用的。可以单独声明一个 `drawerPaperDesktop` class，宽度引用 `drawerWidth` 的值

2021-04-29 12:59 UTC, HFO4 approved these changes

2021-04-29 12:59 UTC, merged

2021-04-29 12:59 UTC, HFO4 commented
已合并，感谢~